### ISSUE TITLE
1.1 Release

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rustfmt#3337]
## Todos for publishing 1.1 via rustup

1. [x] Close #3336. I would like to close this issue before releasing 1.1, as it requires updating `rustc-ap-*` crates.
2. [x] Update the dependency of `racer` to use the same `rustc-ap-*` crates as rustfmt
3. [x] Update the dependency of rls to use the `racer` with the same `rustc-ap-*` crates as rustfmt
4. [ ] Update the submodule in the rustc repository

**Comment by h-michael** [comment]
FYI: @topecongiro 
https://github.com/rust-lang/rust/pull/58356 (these use rust-ap-* v366.0.0)
