### ISSUE TITLE
backwards compatibility issue in the last month or so

### ISSUE THREAD

**Issue by nrc** [rust-lang/rustfmt#3721]
Some time between 2019-06-14 and 2019-07-19, the default formatting changed, this breaks rustfmt's backwards compatibility guarantee.

I see two kinds of changes:

```
-            ConfChangeType::BeginMembershipChange | ConfChangeType::FinalizeMembershipChange => {
-                unimplemented!()
-            }
+            ConfChangeType::BeginMembershipChange | ConfChangeType::FinalizeMembershipChange => unimplemented!(),
```

and

```
-                Datum::Bytes(
-                    "НОЧЬ НА ОКРАИНЕ МОСКВЫ"
-                        .as_bytes()
-                        .to_vec(),
-                ),
+                Datum::Bytes("НОЧЬ НА ОКРАИНЕ МОСКВЫ".as_bytes().to_vec()),
+                Datum::Bytes("НОЧЬ НА ОКРАИНЕ МОСКВЫ".as_bytes().to_vec()),
```

The second seems to require >1 byte characters.

There are many more instances in https://github.com/tikv/tikv/pull/5137/files

Thanks!

**Comment by scampi** [comment]
Below is the list of commits for the range reported by @nrc. Few are mine and probably the second change (about unicode) is probably mine where I didn't gated the changes. I will have a look at this one.

- [ ] c0e616bc1d19eb9b08a5db2f265b8332569e7259 Implement closing-block procedure without relying on missed_span module (#3691)
- [ ] 76e2ba25bd419beedbbc15aec6b4c6aef4deffaf #3665: Implemented (#3689)
- [ ] 66c27c9161b2aa70c2902807be12952bd4a0a62b Add #[ignore] to test that runs external process (#3690)
- [ ] 640b8d0257613bee58f6fdb81356a6167a399737 Update CHANGELOG.md
- [ ] 65931cd09d5be3039d907015234c3fd5325c289d Release 1.3.3
- [ ] e8b2ae16536c37216fda2bc266784c0a4a766c5f Update CHANGELOG.md
- [ ] 89940e541f921b5b22c12a24f6c84e32c691a9a4 Fix bugs related to file-lines (#3684)
- [ ] 6487422b3e0b93645e004c66c32fad5a7ab58b80 fix print-config minimal option (#3687)
- [ ] 0e6896b22951c606b2b78640bb1e3a3ccbb86efe Merge pull request #3683 from calebcartwright/accept-manifest-path
- [ ] 6f67f077529525cb5f96803f17295079656f4058 refactor: simplify manifest_path option checks
- [ ] aef8e935142bbb3b8511691e725d8cd53f4ff213 Merge remote-tracking branch 'upstream/master' into accept-manifest-path
- [ ] 71289e1d230d19f223e45b0abe75ae976f567900 fix 'extra comma inserted due to comment' (#3677)
- [ ] e55fc6be3b3cac1954e5c7d189c62021ef76622a Fix using --help, --verbose, etc. (#3620)
- [ ] 37695b3c45ec8015974359a2f809aa98accd173c Extract configuration snippet tests into own module (#3667)
- [ ] 17cbbd8cbc2d829e0ce07c619a2970a46a3b9b8c feat: add --manifest-path support to cargo fmt
- [ ] 679c8d5f106e8442bf8c4a54609a63df9eb3863c Release 1.3.2
- [ ] c1c532c8ff655002277835599381336adcc3a187 Update CHANGELOG.md
- [ ] 3200af97857cf3712e10fed4113206c1ffe97524 Do not consider macro-origin await as chain item (#3671)
- [ ] ff49b806283050c9e095e0352560256522356c3b fix: handling of --all when dep name and dir name differ (#3664)
- [ ] 44149d6ba4054b80e9d7009431eb2c5e501bb1fe Release 1.3.1
- [ ] 8c29e8be7462da08d1d47674a0b62169cb9f2856 Update rustfmt-config_proc_macro to 0.1.2
- [ ] a8ca806a5e68fe6c342d26d7d123a7e521adec69 Update rustfmt-config_proc_macro to 0.1.1
- [ ] 1f06a8b361dda56defe67d7af56a406cd2fbae08 fix extraction of missing comments when rewriting an empty where clause (#3663)
- [ ] b6f7f24915152c4ecd7ef4520bf2bb759bf4c13b Merge pull request #3661 from calebcartwright/associated-type-bounds
- [ ] d9e42aea74d2f21b067c9140ffdfb14a456b208d tests: add tests for assoscaited_type_bounds fix
- [ ] 1ee51a4125a00a73545a24abe21c041b1cfbefc2 Add support for windows-style paths in ignore patterns (#3633)
- [ ] 731f7d5200f0045efbadeef74e3c6a6e7c1b1c81 fix: handling of associated type bounds
- [ ] e0e2f0db537904b0efa78a106384e62852b806f0 Don't panic on license check errors (#3655)
- [ ] c955b5908e0c699500d1d3dea3481136dd16197d fix: run in sub dirs/workspace member dirs (#3652)
- [ ] 9986b9d01184e9be6390c377942386c4451c22d9 fix internal error for long closure types (#3653)
- [ ] 561653326d158e81c7cd1cd4d6ed34133a33b8fc Add newline after help text (#3650)
- [ ] 26d370e9e52f5c2727b7289e339499aef0b7b3ec remove unreachable!() (#3646)
- [ ] 5b0ce0ed120d71c879848fdbbe8b8d05c442373d avoid not to truncate necessary chars (#3640)
- [ ] 1d19a08ed4743e3c95176fb639ebcd50f68a3313 Format the last expression-statement as expression (#3631)
- [ ] 84c23565901c0d9b7af41d372b9f2d1e2d6c6394 handle unicode chars in closures (#3632)
- [ ] 944fc57e10222e5b0b57772c6a18b21392671c2a tests: ensure min number of system/idempotent tests ran (#3629)
- [ ] aa0c9dd212a051e2c3779cee23c4fd259f26c15d tests: add normalize_doc_attributes config tests (#3630)
- [ ] 4b102fde2ca2cb4921250e0adc1c090dd2d4a579 Merge pull request #3628 from topecongiro/issue-3627
- [ ] a4eab17d7c4cdeee1d0e72ea2a8a5f6a377627f2 Fix is_subpath

**Comment by nrc** [comment]
Thanks @scampi ! Fwiw, I think the breaking change for unicode might be acceptable? If it's a one-off and it is communicated. It is clearly a big fix and shouldn't affect too many users. OTOH, having an opt-in also seems good.
