### ISSUE TITLE
Tracking issue: rustfmt 2.0

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rustfmt#3887]
Also, see [Milestone for 2.0](https://github.com/rust-lang/rustfmt/milestone/8).

## Blocking issues

- [x] Separate rustfmt-lib (#1583) 
- [x] Remove version gates (#3886)
- [x] Update the default edition to 2018 (#3517) 
- [ ] Use different versions of rustfmt-lib crates to enforce stability guarantee (#3841) 

### Help wanted 

- [x] Add `--check` command-line flag to `cargo-fmt` (#3888) 
- [x] Deprecate `--backup` command-line flag
- [x] Deprecate `--skip-children` command-line flag and `skip_children` configuration option (#3389 and #3893) 
- [x] Add `--recursive` command-line flag

## Non-blocking issues

Any issues concerning formatting bugs will be non-blocking.

**Comment by calebcartwright** [comment]
I didn't find any related issues on this, but I'd suggest considering an update/refresh of some sections in the README as part of 2.0 

As an example, the [Limitations](https://github.com/rust-lang/rustfmt#limitations) section starts with several mentions of approaching _1.0_:
> Rustfmt tries to work on as much Rust code as possible, sometimes, the code doesn't even need to compile! As we approach a 1.0 release we are also looking to limit areas of instability; in particular, post-1.0, the formatting of most code should not change as Rustfmt improves. However, there are some things that Rustfmt can't do or can't do well (and thus where formatting might change significantly, even post-1.0). We would like to reduce the list of limitations over time.

**Comment by calebcartwright** [comment]
Also, I'm still working on chains ATM, but I'd be happy to work on adding the `--recursive` flag and/or deprecating the `--backup` flag if those are still up for grabs?

**Comment by topecongiro** [comment]
> I didn't find any related issues on this, but I'd suggest considering an update/refresh of some sections in the README as part of 2.0

Will do. Thanks!

> Also, I'm still working on chains ATM, but I'd be happy to work on adding the --recursive flag and/or deprecating the --backup flag if those are still up for grabs?

Yes, you are more than welcome to work on those :)

**Comment by calebcartwright** [comment]
Just to clarify, the goal is just to deprecate the `--backup` flag, not to entirely remove the flag/FilesWithBackupEmitter/etc., correct?

**Comment by scampi** [comment]
@calebcartwright I would think so, just a deprecation for `--backup`

**Comment by calebcartwright** [comment]
Thanks @scampi! Seems straightforward enough for `--backup`, though in the case of `--skip-children`, won't there be the potential for conflict once `--recursive` is added? 

For example, if a user still has `skip_children` in a rustfmt.toml file, and then rustfmt is invoked with the `--recursive` flag (most likely scenario being via `cargo fmt ...` since that will include `--recursive` by default), what's the expected outcome?

Should rustfmt exit with an error? Or emit a warning and let one of the conflicting options take precedence?

**Comment by scampi** [comment]
Since `rustfmt` is invoked with the `--recursive` flag, it should have higher priority over the `skip_children` option in `rustfmt.toml`.
I think that logic should be applied regardless, not just because of the deprecation here, i.e., CLI flags have precedence over `rustfmt.toml`. What do you think ?

**Comment by calebcartwright** [comment]
I'd vote for rustfmt to exit with an error. From my perspective, `recursive` and `skip_children` are separate, mutually exclusive config options and "failing loudly" in the presence of both seems logical.

It feels like a similar situation as when a user specifies both `--check` and `--emit` flags; you can't have both so rustfmt exits with an error

**Comment by scampi** [comment]
Indeed makes sense @calebcartwright , error it is then!

**Comment by topecongiro** [comment]
Closing this as we are using the GitHub's milestone to track issues for 2.0.

**Comment by Keavon** [comment]
What's the status of rustfmt 2.0's release? The milestone tracking issue only shows one incomplete issue, but it hasn't had activity in months. The `rustfmt-2.0` branch in the repo also has not had a commit since 2019.

**Comment by calebcartwright** [comment]
@Keavon - 2.0 development has been happening on the master branch for a long time, the `rustfmt-2.0` branch hasn't had any activity because it hasn't been used/needed. 
https://github.com/rust-lang/rustfmt/blob/a36bcfaf543f7ca5334bae632b2bb0d5cf382bc0/Cargo.toml#L4

To be perfectly transparent though, rustfmt 2.0 may not happen ever, but even if it does it certainly won't happen any time soon. If and when there will be a 2.0, rest assured that will be communicated loudly and broadly. Until then I'd suggest largely forgetting about it and working with the 1.x versions of rustfmt available today.

You can find a bit more information in #4346, but please note that neither that issue nor this one are intended for status update questions.
