### ISSUE TITLE
Tracking issue for `style_edition`

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#5720]
Tracking issue for the rustfmt specifics of implementing/supporting [RFC 3338](https://rust-lang.github.io/rfcs/3338-style-evolution.html), Style Evolution

## About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and link to this issue

## Steps

* [x] Create new configuration option `style_edition`
* [ ] Soft deprecate `version` option with auto-mapping to corresponding `style_edition` value
* [x] Add `--style-edition` flag to `cargo-fmt` and `rustfmt`
* [ ] Update configuration mechanism to support varying option availability, stability, and default values based on `style_edition`
* [ ] Update CLIs (`cargo-fmt` & `rustfmt`) to support varying surface of option/arg availability and stability
* [ ] Update configuration documentation approaches to delineate by style edition

## Associated Issues/Discussions

* #5650 - Design Discussion for `style_edition`

## Unresolved Questions

* Should the rolling "vNext" variant of `style_edition` be made available on stable? I.e. the current latest formatting-stable version of `style_edition` would be `2021`, where `2024` would be analogous to `version=Two`, so would `2024` only be available on nightly?

## Implementation history

- https://github.com/rust-lang/rustfmt/pull/6247
- https://github.com/rust-lang/rustfmt/pull/6432
- https://github.com/rust-lang/rustfmt/pull/6431
- https://github.com/rust-lang/rust/pull/134929

**Comment by stefnotch** [comment]
Just to confirm, the style edition configuration is still unstable. Is that correct? 

While trying to update the information in `Configuration.md`, we were told that this option is stable.
https://github.com/rust-lang/rustfmt/pull/6654

**Comment by ytmimi** [comment]
`style_edition` is stable. At least 2015, 2018, 2021, and 2024 variants are stable. The 2027 variant is currently unstable.

**Comment by stefnotch** [comment]
Oh then https://github.com/rust-lang/rustfmt/blob/main/Configurations.md#style_edition needs to be updated.

**Comment by ytmimi** [comment]
PRs are welcome.
