### ISSUE TITLE
[GSoC24] Implement `rewrite_result` for AST nodes 

### ISSUE THREAD

**Issue by ding-young** [rust-lang/rustfmt#6206]
This issue tracks the necessary tasks to implement `rewrite_result` for all the nodes that have`rewrite` implementation. 

## Background
Current `rewrite` method returns Option, which means that it gives None without any context when formatting fails. To improve tracking the context of formatting failures, we plan to add a new method `rewrite_result` in Rewrite trait and gradually replace `rewrite` with `rewrite_result`. 

## Target AST nodes 
Below is the list of structs that currently implement the rewrite method. Most of these structs are rustc AST node, but it may be rustfmt representation of AST nodes (ex. Chain). Each task requires both implementing `rewrite_result` for that node and then modifying `rewrite` body with calling `rewrite_result`. Still, `rewrite` signature will remain the same and the return value of `rewrite_result` will be squashed into Option until we are ready to propagate Result upwards.  

`attr.rs`
- [ ] ast::NestedMetaItem
- [ ] ast::MetaItem
- [ ] ast::Attribute
- [ ]  \[ast::Attribute\]

`chains.rs` 
- [ ] ChainItem 
- [ ] Chain 

`expr.rs`
- [ ] ast::Expr
- [ ] ast::Block
- [ ] ControlFlow 

`imports.rs`
- [ ] UseSegment 
- [ ] UseTree 

`items.rs`
- [ ] ast::Local
- [ ] TraitAliasBound 
- [ ] ast::FieldDef
- [ ] OpaqueType 
- [ ] ast::FnRetTy
- [ ] ast::Param

`macros.rs`
- [ ] ast::Item
- [ ] MacroArg 

`matches.rs`
- [ ] ArmWrapper 

`overflow.rs`
- [ ] OverflowableItem

`patterns.rs`
- [ ] RangeOperand 
- [ ] (ast) Pat
- [ ] (ast) PatField
- [ ] TuplePatField 

`stmt.rs`
- [ ] Stmt 

`types.rs`
- [ ] SegmentParam 
- [ ] ast::AssocConstraint 
- [ ] ast::AssocConstraintKind
- [ ] ast::WherePredicate
- [ ] ast::GenericArg
- [ ] ast::AnonConst
- [ ] ast::Lifetime
- [ ] ast::GenericBound
- [ ] ast::GenericBounds
- [ ] ast::GenericParam
- [ ] ast::PolyTraitRef
- [ ] ast::TraitRef
- [ ] ast:Ty

## Future Tasks
Future tasks have two directions: one is propagating errors upward, and the other is generating a Result from downward that can potentially cause failure. Corresponding gh issues will be created after the tasks for this issue are done. 

## Reference 
This issue is part of the Google Summer of Code project. For detailed description, see [GSoC project page](https://summerofcode.withgoogle.com/programs/2024/projects/gHEu3vxc).

**Comment by ding-young** [comment]
### List of `rewrite_***`
We need to complete refactoring following functions to implement `rewrite_result` for `Expr`

- rewrite_array
- rewrite_literal
- rewrite_call
- rewrite_all_pairs
- rewrite_pair 
- rewrite_unary_op
- rewrite_struct_lit
- rewrite_tuple
- rewrite_let
- rewrite_block
- rewrite_block_with_visitor
- rewrite_match
- rewrite_path
- rewrite_assignment
- rewrite_unary_prefix
- rewrite_unary_suffix
- rewrite_closure
- rewrite_chain
- rewrite_macro
- rewrite_index
- rewrite_expr_addrof

### Notable functions that are widely used
- `combine_strs_with_missing_comments` 
- `itemize_list`, `write_list`, Iterator for `ListItems` 
- `rewrite_comment`

**Comment by ding-young** [comment]
## TODO for propagating errors
### Update functions that format top level items to return RewriteResult
These are the list of functions that I have to update.

- [ ] rewrite_reorderable_or_regroupable_items
- [ ] functions in visit_item   
- [ ] Use format_import  
- [ ] Impl format_impl  
- [ ] Trait format_trait  
- [ ] TraitAlias format_trait_alias  
- [ ] ExternCrate rewrite_extern_crate   
- [ ] Struct visit_struct  
- [ ] Mod format_mod   
- [ ] MacCall visit_mac  
- [ ] ForeignMod format_foreign_mod  
- [ ] Static / Const visit_static  
- [ ] Fn (body) visit_fn   
     (only sig) rewrite_required_fn   
- [ ] TyAlias visit_ty_alias_kind  
- [ ] GlobalAsm (nothing to do)  
- [ ] MacroDef rewrite_macro_def  
- [ ] Delegation (currently pushing None since it does not support rewrite delegation)
